openapi: 3.0.0
info:
  title: Consent
  description: API to manage consent
  version: 1.0.0
components:
  schemas:
    DefaultResponse:
      type: object
      properties:
        message:
          type: string
          example: ok
    HeadConsentDocumentsResponseData:
      type: object
      required:
        - list
      properties:
        list:
          type: array
          items:
            type: object
            required:
              - consentId
              - status
              - consentType
              - lastUpdatedAt
              - lastUpdatedBy
              - consentVersion
              - version
              - previewToken
            properties:
              consentId:
                type: string
              status:
                type: string
              consentType:
                type: string
              lastUpdatedAt:
                type: string
              lastUpdatedBy:
                type: string
              consentVersion:
                type: string
              version:
                type: integer
              publishedDate:
                type: string
              cancelledDate:
                type: string
              previewToken:
                type: string
              isLatest:
                type: boolean
    GetConsentDocumentFullResponseData:
      type: object
      required:
        - consentId
        - status
        - contentTh
        - contentEn
        - consentType
        - lastUpdatedAt
        - lastUpdatedBy
        - consentVersion
        - version
        - previewToken
      properties:
        consentId:
          type: string
        contentTh:
          type: string
        contentEn:
          type: string
        draftJsDataTh:
          type: string
        draftJsDataEn:
          type: string
        status:
          type: string
        consentType:
          type: string
        lastUpdatedAt:
          type: string
        lastUpdatedBy:
          type: string
        consentVersion:
          type: string
        version:
          type: integer
        publishedDate:
          type: string
        cancelledDate:
          type: string
        previewToken:
          type: string
        isLatest:
          type: boolean
    UpdateConsentDocumentRequestData:
      type: object
      required:
        - consentId
        - draftJsDataTh
        - draftJsDataEn
        - contentTh
        - contentEn
        - version
      properties:
        draftJsDataTh:
          type: string
        draftJsDataEn:
          type: string
        consentId:
          type: string
        contentTh:
          type: string
        contentEn:
          type: string
        version:
          type: integer
    PublishRequestData:
      type: object
      required:
        - consentId
        - version
      properties:
        consentId:
          type: string
        version:
          type: integer
    GetConsentToAcceptResponseData:
      type: object
      properties:
        consentVersion:
          type: string
        content:
          type: string

paths:
  /consents/getConsentDocument:
    get:
      tags:
        - consent
      summary: Get consent document such as Terms and Conditions, Privacy Policy ...
      description: Get consent document such as Terms and Conditions, Privacy Policy ...
      operationId: getConsentDocument
      parameters:
        - in: query
          name: documentType
          required: true
          description: TC_USER | TC_USER_X_PRIVACY | TC_CMS | PRIVACY | COOKIE | TC_PAYMENT
          example: TC_USER
          schema:
            type: string
            enum:
              - TC_USER
              - TC_CARRIAGE
              - TC_KYC
              - PRIVACY
        - in: query
          name: language
          required: true
          description: th | en
          example: en
          schema:
            type: string
            enum:
              - th
              - en
        - in: query
          name: version
          required: false
          description: consent version, latest if not specified
          example: "1"
          schema:
            type: string
            minLength: 0
            maxLength: 10
        - in: query
          name: previewToken
          required: false
          description: needed to see DRAFT consent
          schema:
            type: string
            minLength: 0
            maxLength: 1000
      responses:
        200:
          description: The consent document HTML
          content:
            text/html:
              schema:
                type: string
  /consents/getConsentToAccept:
    get:
      tags:
        - consent
      summary: getConsentToAccept
      description: getConsentToAccept
      operationId: getConsentToAccept
      parameters:
        - in: query
          name: documentType
          required: true
          description: TC_USER | TC_USER_X_PRIVACY | TC_CMS | PRIVACY | COOKIE | TC_PAYMENT
          example: TC_USER
          schema:
            type: string
            enum:
              - TC_USER
              - TC_CARRIAGE
              - TC_KYC
              - PRIVACY
        - in: query
          name: language
          required: true
          description: th | en
          example: en
          schema:
            type: string
            enum:
              - th
              - en
        - in: query
          name: acceptedConsentVersion
          required: false
          description: previously accepted version for this document
          example: "1"
          schema:
            type: string
            minLength: 0
            maxLength: 10
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetConsentToAcceptResponseData"
  /consents/headConsentDocuments:
    get:
      tags:
        - consent
      summary: headConsentDocuments
      description: headConsentDocuments
      operationId: headConsentDocuments
      responses:
        200:
          description: list of consent documents without full content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HeadConsentDocumentsResponseData"
  /consents/getConsentDocumentFull:
    get:
      tags:
        - consent
      summary: getConsentDocumentFull
      description: getConsentDocumentFull
      operationId: getConsentDocumentFull
      parameters:
        - in: query
          name: consentId
          required: true
          description: uuid of the consent document
          schema:
            type: string
            minLength: 1
            maxLength: 50
      responses:
        200:
          description: Consent document with full content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetConsentDocumentFullResponseData"
  /consents/updateConsentDocument:
    post:
      tags:
        - consent
      summary: updateConsentDocument
      description: updateConsentDocument
      operationId: updateConsentDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateConsentDocumentRequestData"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultResponse"
  /consents/publish:
    post:
      tags:
        - consent
      summary: publish
      description: publish
      operationId: publish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublishRequestData"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultResponse"
