openapi: 3.0.0
info:
  title: Payment
  description: API to manage payments
  version: 1.0.0
components:
  schemas:
    DefaultResponse:
      type: object
      properties:
        message:
          type: string
          example: "ok"
    GenerateWebPayUrlResponseData:
      type: object
      required:
        - url
      properties:
        url:
          type: string

paths:
  /payments/generateWebPayUrl:
    get:
      tags:
        - payment
      summary: generateWebPayUrl
      description: generateWebPayUrl
      operationId: generateWebPayUrl
      parameters:
        - in: query
          name: amount
          description: amount
          required: true
          schema:
            type: number
            minimum: 0
            maximum: 1000000
        - in: query
          name: orderId
          description: orderId
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 15
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateWebPayUrlResponseData"
