openapi: 3.0.0
info:
  title: Setting
  description: API to manage settings
  version: 1.0.0
components:
  schemas:
    DefaultResponse:
      type: object
      properties:
        message:
          type: string
          example: "ok"
    ListGeneralSettingsResponseData:
      type: object
      properties:
        mobileMinimumSupportedVersion:
          type: string
        mobileMinimumSupportedVersionAndroid:
          type: string
        mobileIdleTimeout:
          type: integer
        cmsIdleTimeout:
          type: integer
        callCenterPhoneNo:
          type: string
        contactEmail:
          type: string
        facebookUrl:
          type: string
        youtubeUrl:
          type: string
        twitterUrl:
          type: string
        instagramUrl:
          type: string
        contactWebsite:
          type: string
        contactAddress:
          type: string
        orderImportExampleUrl:
          type: string

    Settings:
      type: object
      properties:
        mobile:
          type: object
          required:
            - iosMinVersion
            - androidMinVersion
            - idleTimeout
          properties:
            iosMinVersion:
              type: string
              pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
            androidMinVersion:
              type: string
              pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
            idleTimeout:
              type: integer
              minimum: 0
        cms:
          type: object
          required:
            - idleTimeout
          properties:
            idleTimeout:
              type: integer
              minimum: 0
            orderImportExampleUrl:
              type: string
              pattern: "^https://.+"
              maxLength: 1000
        contactInformation:
          type: object
          required:
            - callCenterPhoneNo
            - contactEmail
          properties:
            callCenterPhoneNo:
              type: string
              minLength: 1
              maxLength: 100
            contactEmail:
              type: string
              format: email
            facebookUrl:
              type: string
              pattern: "^https://.+"
              maxLength: 100
            youtubeUrl:
              type: string
              pattern: "^https://.+"
              maxLength: 100
            twitterUrl:
              type: string
              pattern: "^https://.+"
              maxLength: 100
            instagramUrl:
              type: string
              pattern: "^https://.+"
              maxLength: 100
            contactAddressTh:
              type: string
              minLength: 1
              maxLength: 1000
            contactAddressEn:
              type: string
              minLength: 1
              maxLength: 1000
            contactWebsite:
              type: string
              minLength: 1
              maxLength: 1000

paths:
  /settings/listGeneralSettings:
    get:
      tags:
        - setting
      summary: listGeneralSettings
      description: listGeneralSettings
      operationId: listGeneralSettings
      responses:
        200:
          description: The list of banks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListGeneralSettingsResponseData"
  /settings/getSettings:
    get:
      tags:
        - setting
      summary: getSettings
      description: getSettings
      operationId: getSettings
      parameters:
        - in: query
          name: group
          description: list of group names
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - mobile
                - cms
                - contactInformation
      responses:
        200:
          description: the settings
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Settings"
  /settings/updateSettings:
    post:
      tags:
        - setting
      summary: updateSettings
      description: updateSettings
      operationId: updateSettings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Settings"
      responses:
        200:
          description: the settings
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultResponse"
