openapi: 3.0.0
info:
  title: Usage
  description: API to manage usage
  version: 1.0.0
components:
  schemas:
    DefaultResponse:
      type: object
      properties:
        message:
          type: string
          example: 'ok'
    ReportErrorRequestData:
      type: object
      properties:
        images:
          type: array
          items:
            type: string
        timestamp:
          type: string
        appState:
          type: string
        principalError:
          type: string

paths:
  /usages/reportError:
    post:
      tags:
        - usage
      summary: Report error
      description: Report error
      operationId: reportError
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportErrorRequestData'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'