openapi: 3.0.0
info:
  title: Users
  description: API to manage users
  version: 1.0.0
components:
  schemas:
    DefaultResponse:
      type: object
      properties:
        message:
          type: string
    UpdateUserRequestData:
      type: object
      required:
        - profileImageUrl
      properties:
        profileImageUrl:
          type: string

paths:
  /users/updateUser:
    post:
      tags:
        - user
      summary: update some information of a user
      description: update some information of a userx
      operationId: updateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequestData'
       
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'